apiVersion: v1
kind: Service
metadata:
  name: argo-test-app1
spec:
  type: LoadBalancer
  selector:
    app: argo-test-app1
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: http
